### ISSUE TITLE
Create a version compatible with solana v1.18.0?

### ISSUE THREAD

**Issue by kapilsinha** [raydium-io/raydium-library#2]
Older versions of solana-sdk and solana-program are largely broken, and the advice seems to be upgrade old versions to the latest v1.18.0 version:
https://github.com/coral-xyz/anchor/issues/2953

Can the raydium (library, amm, clmm) repos be updated to this one?

**Comment by shrimpwtf** [comment]
Bump on this. The example code here doesnt even fucking compile unless you explicitly use their cargo.lock because its so wildly outdated and all their libraries it hooks into use wildly different versions. Like literally compile and run it, then clean cargo cache and delete cargo.lock and watch it magically refuse to compile. This is absolutely unacceptable for a company of this size... Literally such a big company in crypto reaping in likely millions daily can't even keep this upto date.

**Comment by popconst** [comment]
bump! I cannot use the raydium sdk in any reasonable way with solana  2.0 + . 

And there seems to be zero interest from the team to actually do anything with it.  

very sad.

**Comment by RainRaydium** [comment]
We are so sorry for this, because relying on the latest anchor version will cause the contract stack to overflow [PR.](https://github.com/coral-xyz/anchor/pull/2939) . 
We will keep updating after the release of anchor 0.31. Thank you for your understanding.
